
DROP TABLE IF EXISTS shoppinglist_product CASCADE;
DROP TABLE IF EXISTS shoppinglist_usergroup CASCADE;
DROP TABLE IF EXISTS shoppinglist CASCADE;
DROP TABLE IF EXISTS shop_product CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS unit CASCADE;
DROP TABLE IF EXISTS shop_usergroup CASCADE;
DROP TABLE IF EXISTS shop CASCADE;
DROP TABLE IF EXISTS usergroup_users CASCADE;
DROP TABLE IF EXISTS usergroup CASCADE;
DROP TABLE IF EXISTS users CASCADE;

